import admin from 'firebase-admin';
admin.initializeApp();

/* eslint-disable max-len */

export { default as addToAdminList } from './accountCreationAndVerification/addToAdminList';
export { default as createUserOnFirestore } from './accountCreationAndVerification/createUserOnFirestore';
export { default as deleteUnverifiedAccounts } from './accountDeletion/deleteUnverifiedAccounts';
export { default as deleteUser } from './accountDeletion/deleteUser';
export { default as deleteUserOnFirestore } from './accountDeletion/deleteUserOnFirestore';
export { default as deleteQuestionFromPQ } from './deleteQuestionFromPQ';
export { default as getAllCourses } from './getAllCourses';
export { default as getCourseData } from './getWebCourse';
export { default as getAllCoursesPreview } from './getAllCoursesPreview';
export { default as getCourseMobile } from './getMobileCourse';
export { default as getCourseProgress } from './getCourseProgress';
export { default as getUserByIdMobile } from './getUser';
export { default as getUserFollowedCourses } from './getFollowedCourses';
export { default as isUserATeacher } from './accountCreationAndVerification/isUserATeacher';
export { default as listTeacherEmails } from './listTeacherEmails';
export { default as registerCourse } from './courseCreationAndModification/registerCourse';
export { default as removeCourseFromFollowedCourses } from './accountModification/unfollowCourse';
export { default as setMockData } from './mocks/setMockData';
export { default as updateLessonProgress } from './accountModification/updateLessonProgress';
export { default as updateCourse } from './courseCreationAndModification/updateCourse';
export { default as upgradeUserToTeacher } from './accountCreationAndVerification/upgradeUserToTeacher';
export { default as getDummyAnalytics } from './mocks/getDummyAnalytics';
export { default as followCourse } from './accountModification/followCourse';
export { default as getDummyFailedQuestions } from './mocks/getDummyFailedQuestions';
export { default as publishCourse } from './courseCreationAndModification/publishCourse';
export { default as completeQuestion } from './completeQuestion';
export { default as returnFailedQuestionsIds } from './getFailedQuestions';
export { default as archiveCourse } from './courseCreationAndModification/archiveCourse';
export { default as deleteCourse } from './courseCreationAndModification/deleteCourse';
export { default as getAllUsers } from './accountModificationAdminPage/getAllUsers';
export { default as getPendingUsers } from './accountModificationAdminPage/getPendingUsers';
export { default as updateUsersLevel } from './accountModificationAdminPage/updateUsersLevel';
export { default as getUserAuthLevel } from './accountCreationAndVerification/getUserAuthLevel';
export { default as removeQuestionFromFailedQuestions } from './removeQuestionFromFailedQuestions';
export { default as getAllPendingUsers } from './getAllPendingUsers';
export { default as getCourseAnalytics } from './getCourseAnalytics';
export { default as getPriorityQueueQuestions } from './getPriorityQueueQuestions';
export { default as adminDeleteUser } from './accountDeletion/adminDeleteUser';
